---
title: "template"
author: "Bowen Xiao"
date: "September 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Package for NHTS

```{r}
library(summarizeNHTS)
```

## Data Load

```{r}
nhts_data <- read_data("2017", "./data")
```

## Generating Estimates

The detailed configurations of "IS_BIKER" and "USES_TNC" are in `./data/csv/2017/derived_variable_config.csv`.

```{r}
summarize_data(
  data = nhts_data,
  agg = "person_count",
  by = c("IS_BIKER", "USES_TNC"),
  prop = TRUE
)
```

```{r}
summarize_data(
  data = nhts_data,
  agg = "person_count",
  by = c("R_RACE", "USES_TNC"),
  prop = TRUE
)
```

```{r}
summarize_data(
  data = nhts_data,
  agg = "person_count",
  by = c("EDUC", "IS_BIKER"),
  prop = TRUE
)
```

## Visualizing Estimates

```{r}
statistic_tnc <- summarize_data(
  data = nhts_data,
  agg = "person_count",
  subset = 'USES_TNC=="1"',
  by = "HHSTFIPS",
  exclude_missing = TRUE
)

make_map(statistic_tnc)
```

```{r}
statistic_bike <- summarize_data(
  data = nhts_data,
  agg = "person_count",
  subset = 'IS_BIKER=="1"',
  by = "HHSTFIPS",
  exclude_missing = TRUE
)

make_map(statistic_bike)
```

```{r}
statistic_bike_travel <- summarize_data(
  data = nhts_data,
  agg = "household_count",
  subset = 'IS_BIKE_TRAVELER=="1"',
  by = "HHSTFIPS",
  exclude_missing = TRUE
)

make_map(statistic_bike_travel)
```

```{r}
statistic_hybird <- summarize_data(
  data = nhts_data,
  agg = "vehicle_count",
  subset = 'IS_HYBIRD=="1"',
  by = "HHSTFIPS",
  exclude_missing = TRUE
)

make_map(statistic_hybird)
```

## Replicate Weights

```{r}
summarize_data(
  data = nhts_data,
  agg = "person_count",
  by = c("USES_TNC"),
  prop = TRUE
)
```

```{r}
df_tnc <- as.data.frame(nhts_data$data$person)
df_tnc <- df_tnc[,which(names(df_tnc) %in% c("HOUSEID","PERSONID","USES_TNC"))]
df_tnc <- merge(df_tnc,as.data.frame(nhts_data$weights$person),by=c("HOUSEID","PERSONID"))
df_tnc <- df_tnc[complete.cases(df_tnc),]
(est <- sum(df_tnc[df_tnc$USES_TNC=='1',]$WTPERFIN)/sum(df_tnc$WTPERFIN))
var <- 0
for(i in 5:102){
  temp <- sum(df_tnc[df_tnc$USES_TNC=='1',i])/sum(df_tnc[,i])
  var <- var + 6*(temp - est)^2/7
}
sqrt(var)
```

## m-out-of-n Bootstrap

```{r}
library(dplyr)
set.seed(2017)
est1 <- c()
for(i in 1:1000){
  temp <- sample_n(df_tnc,0.3*nrow(df_tnc),replace=TRUE)
  est1 <- c(est1,sum(temp[temp$USES_TNC=='1',]$WTPERFIN)/sum(temp$WTPERFIN))
}
mean(est1)
sd(est1)
hist(est1)
```

```{r}
est2 <- c()
for(i in 1:1000){
  temp <- sample_n(df_tnc,0.05*nrow(df_tnc),weight=df_tnc$WTPERFIN,replace=TRUE)
  est2 <- c(est2,mean(temp$USES_TNC=='1'))
}
mean(est2)
sd(est2)
hist(est2)
```

## Bayesian Belief Network

```{r}
#data
df_person <- nhts_data$data$person
df_person <- data.frame(tnc_user=df_person$USES_TNC,
                       education=df_person$EDUC,
                       race=df_person$R_RACE,
                       health=df_person$HEALTH,
                       age=df_person$R_AGE,
                       gender=df_person$R_SEX)
lambda <- function(x) x >= 0
df_person[,1:6] <- lapply(df_person[,1:6], as.numeric)
df_person <- df_person[complete.cases(df_person)&
                        lambda(df_person$education)&
                        lambda(df_person$race)&
                        lambda(df_person$health)&
                        lambda(df_person$gender),]

#discretize continuous variables
library(arules)
df_person$age <- discretize(df_person$age, method = "frequency", breaks = 5)

#fatorize variables
df_person[,1:6] <- lapply(df_person[,1:6], as.character)
df_person[,1:6] <- lapply(df_person[,1:6], factor)

#BNN
library(bnlearn)
boot <- boot.strength(df_person, R = 500, algorithm = "hc", algorithm.args = list(score = "bde", iss = 10))
print(boot[boot$strength > 0.85 & boot$direction >= 0.5, ])
avg.boot <- averaged.network(boot,threshold = 0.85)
avg.boot <- skeleton(avg.boot)
plot(avg.boot)
```

## Random Forrest

```{r}
#merging "person" and "household"
df_person <- nhts_data$data$person
df_household <- nhts_data$data$household
df <- as.data.frame(merge(df_person, df_household, by='HOUSEID'))

#preprocessing
df <- df[,-which(names(df) %in% c("IS_BIKER"))]
df <- df[,3:ncol(df)]
df <- df[complete.cases(df),]
lambda <- function(x) cut(x, breaks=unique(c(quantile(x))),include.lowest=TRUE)
for(i in 1:ncol(df)){
  if(is.numeric(df[,i])){
    df[df[,i]>=0,i] <- lambda(df[df[,i]>=0,i])
  }
}
df[,1:ncol(df)] <- lapply(df, factor)
index <- c()
for(i in 1:ncol(df)){
  if(length(levels(df[,i]))>53){
    index <- c(index,i)
  }
}
df <- df[,-index]

#random forrest
library(randomForest)
library(caret)
fit <- randomForest(USES_TNC~., data=df, maxnodes=20)
varImpPlot(fit,type=2)
```